[workspace]
members = [
    "crates/android",
    "crates/desktop",
    "crates/game",
]

resolver = "2"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
